export const SECTOR_CATEGORIES = {
    A: 'Agriculture, forestry and fishing',
    B: 'Mining and quarrying',
    C: 'Manufacturing',
    D: 'Electricity, gas, steam and air conditioning supply',
    E: 'Water supply; sewerage, waste management',
    F: 'Construction',
    G: 'Wholesale and retail trade',
    H: 'Transportation and storage',
    I: 'Accommodation and food service activities',
    J: 'Information and communication',
    K: 'Financial and insurance activities',
    L: 'Real estate activities',
    M: 'Professional, scientific and technical activities',
    N: 'Administrative and support service activities',
    O: 'Public administration and defence',
    P: 'Education',
    Q: 'Human health and social work activities',
    R: 'Arts, entertainment and recreation',
    S: 'Other service activities',
    T: 'Households as employers',
    U: 'Activities of extraterritorial organisations',
  }